name: run-tests

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  php8x-laravel-version-tests:

    name: Laravel - PHP ${{ matrix.php }} - TestBench ${{ matrix.testbench}} - ${{ matrix.os }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.1, "8.0"]
        phpunit: [^9.3]
        testbench: [^6.22]
        dependency-prefer: [prefer-stable, prefer-lowest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, intl, mbstring
          coverage: none

      # find out composer's cache directory on the current os - for the "Cache dependencies (composer)" step below
      - name: Determine composer's cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-testbench-${{ matrix.testbench }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies (composer)
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit

  php7x-laravel-version-tests:

    name: Laravel - PHP ${{ matrix.php }} - TestBench ${{ matrix.testbench}} - ${{ matrix.os }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 7.3, 7.2, 7.1, "7.0"]
        testbench: [^6.0, ^5.0, ^4.0, 3.8.*, 3.7.*, 3.6.*, 3.5.*, 3.4.*, 3.3.*, 3.2.*]
        dependency-prefer: [prefer-stable, prefer-lowest]
        include:
          - testbench: ^6.0
            phpunit: "^8.5 | ^9.0"
          - testbench: ^5.0
            phpunit: "^8.5 | ^9.0"
          - testbench: ^4.0
            phpunit: "^8.4 | ^9.0"
          - testbench: 3.8.*
            phpunit: "^7.5 | ^8.0"
          - testbench: 3.7.*
            phpunit: ^7.0
          - testbench: 3.6.*
            phpunit: ^7.0
          - testbench: 3.5.*
            phpunit: ~6.0
          - testbench: 3.4.*
            phpunit: ~5.7
          - testbench: 3.3.*
            phpunit: "~4.8 | ~5.0"
          - testbench: 3.2.*
            phpunit: "~4.8 | ~5.0"
        exclude:
          - php: "7.0"
            testbench: 3.2.*
          - php: "7.0"
            testbench: 3.6.*
          - php: "7.0"
            testbench: 3.7.*
          - php: "7.0"
            testbench: 3.8.*
          - php: "7.0"
            testbench: ^4.0
          - php: "7.0"
            testbench: ^5.0
          - php: "7.0"
            testbench: ^6.0
          - php: 7.1
            testbench: ^4.0
          - php: 7.1
            testbench: ^5.0
          - php: 7.1
            testbench: ^6.0
          - php: 7.2
            testbench: ^5.0
          - php: 7.2
            testbench: ^6.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, intl, mbstring
          coverage: none

      # find out composer's cache directory on the current os - for the "Cache dependencies (composer)" step below
      - name: Determine composer's cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-testbench-${{ matrix.testbench }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies (composer)
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit

  OS-tests:

    name: OS - PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest]
        php: [8.1, "8.0", 7.4]
        testbench: [^6.0, ^5.0]
        dependency-prefer: [prefer-stable, prefer-lowest]
        include:
          - php: 8.1
            phpunit: ^9.3
          - php: "8.0"
            phpunit: ^9.3
          - php: 7.4
            phpunit: "~4.8 | ^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, fileinfo, intl, mbstring
          coverage: none

      # find out composer's cache directory on the current os - for the "Cache dependencies (composer)" step below
      - name: Determine composer's cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies (composer)
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-os-${{ matrix.os }}-dependency-prefer-${{ matrix.dependency-prefer }}-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies (composer)
        run: |
          composer require "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests (standalone group)
        run: vendor/bin/phpunit --group=standalone
